### ISSUE TITLE
Discrete endpoints for network operations

### ISSUE THREAD

**Issue by mgax** [liquidinvestigations/docs#2]
Right now, there is one API endpoint, `PUT /networking/config`, which basically rewrites the entire network config. There is a race condition if two instances of the admin UI are used simultaneously to change different parts of the configuration.

I propose we split that up into a few different endpoints:
* `PUT /networking/lan` for [the "lan" dictionary](https://github.com/liquidinvestigations/docs/blob/508d05be/apiary.apib#L76-L85)
* `PUT /networking/wan/static` or `DELETE /networking/wan/static` for a [static WAN address](https://github.com/liquidinvestigations/docs/blob/508d05be/apiary.apib#L76-L85)
* `POST /networking/wan/wifi/networks` to add/remove a single [SSID](https://github.com/liquidinvestigations/docs/blob/508d05be/apiary.apib#L93-L96)
* `PUT /networking/sshd` to set ssh on/off and port number
* `POST /networking/keys` to add/remove a single ssh key

**Comment by alsegno** [comment]
It's not a race condition -- if two people are editing, then the last one to click 'save' gets their changes committed, right? It should be rare enough that we can just document it away for now.

I think it's less effort just to do the monolithic config -- how often is one person going to want to change the SSID while another is changing the LAN dictionary or something?

**Comment by alsegno** [comment]
And anyway, this doesn't solve the 'race condition' you describe does it? What if these two admin UI users are both trying to change something in the same endpoint?

To fix this I think you either need to push any config changes to the UI 'live' so that the other user can see them before changing (which could be unsettling to the user), or you need to implement some kind of locking like 'these settings are currently being changed by some other admin user, come back later and then you can try'. Making more granular endpoints doesn't do that.

**Comment by mgax** [comment]
Right, so we have 3 options:
1. submit the entire network form as a single entity and overwrite the previous state, without any locking
2. like above, but with locking
3. live-commit any changes as the user makes them; this requires the server to push other people's updates back to the UI in real time

Option 2 sounds crazy, because good locking (and expiry of the lock) is tricky and unexpected to the user. Option 3 is actually what [sandstorm](https://sandstorm.io) does, and it's pretty neat, but probably a fair amount of work.

Can we at least find a way of detecting when two admins overwrite each other's settings (like, they both add a wifi network)?

**Comment by alsegno** [comment]
Do we keep any user session state or not? We could just make it so only one admin can log in at once.

**Comment by mgax** [comment]
That's "option 2", which I believe is tricky. Where do we keep the lock - in the database, on disk? How does it expire? Does the javascript code have to ping the server regularly in order to maintain the lock?

**Comment by alsegno** [comment]
Does this help us?

https://sookocheff.com/post/api/optimistic-locking-in-a-rest-api/

**Comment by alsegno** [comment]
Here's a flask implementation that assumes you're okay with monkeypatching Werkzeug:

http://flask.pocoo.org/snippets/95/

I don't know enough about django to know what to do if it's taking care of our API.

**Comment by mgax** [comment]
Huh, that's interesting. We should check if the UI folks like the idea.

**Comment by alsegno** [comment]
https://martinfowler.com/bliki/TwoHardThings.html

**Comment by m-nic** [comment]
There are a couple of working solutions mentioned above. I think this scenario where multiple admins edit the same values would  be quite rare, however we may want to have basic protection in a while. 

Here is my suggestion:

Whenever an admin would access a page we should call a page status API (this would return either some success value or an error indicating who is editing the page - if we want to display that), if successful we call the page locking API (allowing form changes) and when leaving the page we should call the page unlocking API (if the current user was the one editing). 
For the "locked" admin  we could additionally ping the page status API once in like 10 seconds, if not we can simply instruct the admin to come back to the page later.

This would inform the admin that some other admin xyz is editing the page and they could sort things by communicating/messaging (maybe display a message xyz button). 
Having to submit the form and error out that someone is using that would be bad UX wise, pushing other peoples changes back to the UI I think it s over-complicated and it's strange for the user.

We could have some API's like: ` /page/<page>/status` ` /page/<page>/lock` `/page/<page>/unlock` - store the flags in a DB and manage them nicely in the UI.
IMO this would be the proper choice.

**Comment by mgax** [comment]
If we do implement locking, we should lock the whole admin area, not specific pages. And there should be a button to override the lock, in case it's obviously stale, instead of having to wait for it to expire. Dokuwiki implements this nicely.

**Comment by gabriel-v** [comment]
done
