### ISSUE TITLE
Complete WiFi-Adapters.md with chipset model.

### ISSUE THREAD

**Issue by mrc-toader** [liquidinvestigations/docs#5]
Add chipset model and version to each dongle in linked doc, because most of them may have the exact same one.

https://github.com/liquidinvestigations/docs/blob/master/manual/WiFi-Adapters.md

Optionally, look into what firmware they use, maybe the interface dropping of some could be fixed with a package or kernel update?

**Comment by mgax** [comment]
Let's add information to the manual when we find that information. It makes no sense to create issues for this.
