### ISSUE TITLE
Document how to run liquid in factory

### ISSUE THREAD

**Issue by mrc-toader** [liquidinvestigations/docs#9]
In order to perform manual tests on the cloud image.

**Comment by mgax** [comment]
Here's the documentation:

https://github.com/liquidinvestigations/docs/blob/master/manual/Cloud_Vm.md

cc @gabriel-v @m-nic i know you guys are using this method, can you please sanity check what i wrote? thanks!

**Comment by mrc-toader** [comment]
Documented here by @gabriel-v , works. 
`https://github.com/liquidinvestigations/web-ui-deployment-scripts`
